### ISSUE TITLE
Workspace Select Should Only Be Visible on /w/:wid Domains

### ISSUE THREAD

**Issue by MarcDAFrame** [AgoraCloud/ui#47] opened 2021-03-23 18:42 UTC
Currently when on other domains besides `/w/:wid` (such as `/admin`) users can see the Workspace Select.

This causes some errors in the console because the Select is 'uncontrolled'

**Comment by MarcDAFrame** [comment] 2021-03-23 19:18
![image](https://user-images.githubusercontent.com/12240832/112205275-0311b680-8beb-11eb-8da2-29591d3add1e.png)

**Comment by saidghamra** [comment] 2021-09-10 21:08
We tried to replicate this today but we could not. Regardless, we will keep our eyes on the console logs. If the issue is not observed in a few weeks, we will close this.

**Comment by saidghamra** [comment] 2021-11-02 00:24
Already fixed via @MarcDAFrame's package integration in #66

**Closed by saidghamra** 2021-11-02 00:24 UTC
Labels: bug, priority:high
